package domain

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// StockMoveType enumerates the allowed stock movement kinds.
type StockMoveType string

const (
	StockMoveIn        StockMoveType = "IN"
	StockMoveOut       StockMoveType = "OUT"
	StockMoveTransfer  StockMoveType = "TRANSFER"
	StockMoveAdjust    StockMoveType = "ADJUST"
	StockMoveReserve   StockMoveType = "RESERVE"
	StockMoveUnreserve StockMoveType = "UNRESERVE"
)

var (
	// ErrInvalidQuantity is returned when a negative quantity is passed to an
	// inventory-mutating method.
	ErrInvalidQuantity = errors.New("quantity must not be negative")
	// ErrInsufficientStock is returned when a reservation would exceed the
	// currently available quantity.
	ErrInsufficientStock = errors.New("insufficient available stock")
)

// Quantity is a non-negative count of stock units. Constructing one via
// NewQuantity is the compile-time-adjacent guarantee that "stock can't go
// negative" — callers that already validated non-negative input (e.g. rows
// read back from this app's own database) may convert directly via
// Quantity(n) instead of re-validating trusted data.
type Quantity int

// NewQuantity constructs a Quantity, rejecting negative input.
func NewQuantity(n int) (Quantity, error) {
	if n < 0 {
		return 0, ErrInvalidQuantity
	}
	return Quantity(n), nil
}

// Int returns the underlying int, for arithmetic and passing to SQL query args.
func (q Quantity) Int() int {
	return int(q)
}

type InventoryItem struct {
	ID             uuid.UUID  `json:"id"`
	VariantID      *uuid.UUID `json:"variant_id,omitempty"`
	Description    *string    `json:"description,omitempty"`
	TrackInventory bool       `json:"track_inventory"`
	CreatedAt      time.Time  `json:"created_at"`
}

type InventoryLevel struct {
	ID              uuid.UUID `json:"id"`
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	LocationID      uuid.UUID `json:"location_id"`
	AvailableQty    Quantity  `json:"available_qty"`
	ReservedQty     Quantity  `json:"reserved_qty"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// Reserve moves qty units from AvailableQty to ReservedQty. It returns
// ErrInvalidQuantity if qty is negative, or ErrInsufficientStock if qty
// exceeds the currently available quantity. On success it mutates l in place.
func (l *InventoryLevel) Reserve(qty Quantity) error {
	if qty < 0 {
		return ErrInvalidQuantity
	}
	if qty > l.AvailableQty {
		return ErrInsufficientStock
	}
	l.AvailableQty -= qty
	l.ReservedQty += qty
	return nil
}

type StockMove struct {
	ID              uuid.UUID     `json:"id"`
	InventoryItemID uuid.UUID     `json:"inventory_item_id"`
	FromLocationID  *uuid.UUID    `json:"from_location_id,omitempty"`
	ToLocationID    *uuid.UUID    `json:"to_location_id,omitempty"`
	MoveType        StockMoveType `json:"move_type"`
	Quantity        Quantity      `json:"quantity"`
	CreatedBy       *uuid.UUID    `json:"created_by,omitempty"`
	Reason          *string       `json:"reason,omitempty"`
	CreatedAt       time.Time     `json:"created_at"`
}

// ReservationStatus enumerates the allowed reservation lifecycle states.
type ReservationStatus string

const (
	ReservationActive   ReservationStatus = "ACTIVE"
	ReservationReleased ReservationStatus = "RELEASED"
	ReservationExpired  ReservationStatus = "EXPIRED"
)

// Reservation is a time-bounded hold of one inventory item for one order.
type Reservation struct {
	ID              uuid.UUID         `json:"id" db:"id"`
	InventoryItemID uuid.UUID         `json:"inventory_item_id" db:"inventory_item_id"`
	LocationID      uuid.UUID         `json:"location_id" db:"location_id"`
	OrderID         uuid.UUID         `json:"order_id" db:"order_id"`
	Quantity        Quantity          `json:"quantity" db:"quantity"`
	ReservedAt      time.Time         `json:"reserved_at" db:"reserved_at"`
	ExpiresAt       time.Time         `json:"expires_at" db:"expires_at"`
	Status          ReservationStatus `json:"status" db:"status"`
	ReleasedAt      *time.Time        `json:"released_at,omitempty" db:"released_at"`
}

// ReservationRequestItem is a caller-supplied checkout item: the public
// product-variant identifier and the requested positive whole-number quantity.
type ReservationRequestItem struct {
	VariantID uuid.UUID
	Quantity  Quantity
}

// CreateReservationItem carries one canonical request item plus the UUIDv7
// identifiers generated by the use case for the reservation and its
// RESERVE stock movement.
type CreateReservationItem struct {
	VariantID     uuid.UUID
	Quantity      Quantity
	ReservationID uuid.UUID
	StockMoveID   uuid.UUID
}

// CreateReservationInput is the use-case-to-repository contract for creating
// one atomic checkout reservation. ExpiresAt is the caller-owned, UTC
// normalized instant every new hold in the set must persist unchanged.
type CreateReservationInput struct {
	OrderID   uuid.UUID
	ExpiresAt time.Time
	Items     []CreateReservationItem
}

// ReservationItemResult is one persisted reservation in the response.
type ReservationItemResult struct {
	ReservationID uuid.UUID         `json:"reservationId"`
	VariantID     uuid.UUID         `json:"variantId"`
	Quantity      Quantity          `json:"qty"`
	Status        ReservationStatus `json:"status"`
	ExpiresAt     time.Time         `json:"expiresAt"`
}

// ReservationResult is the persisted outcome of one checkout reservation.
type ReservationResult struct {
	OrderID uuid.UUID               `json:"orderId"`
	Retried bool                    `json:"-"`
	Items   []ReservationItemResult `json:"items"`
}

// Stable reservation errors.
var (
	// ErrReservationValidation is returned for malformed or ambiguous input
	// (empty items, nil IDs, non-positive quantities, duplicate variants).
	ErrReservationValidation = errors.New("items must contain unique variant IDs and positive whole-number quantities")
	// ErrReservationVariantNotFound is returned when a public variant ID does
	// not resolve to a non-deleted variant.
	ErrReservationVariantNotFound = errors.New("variant not found")
	// ErrVariantNotReservable is returned when a variant's inventory item is
	// not tracked.
	ErrVariantNotReservable = errors.New("variant is not reservable")
	// ErrReservationInventoryNotFound is returned when the default location or
	// an eligible inventory level cannot be resolved.
	ErrReservationInventoryNotFound = errors.New("reservable inventory was not found for the requested variant")
	// ErrReservationConflict is returned when an order ID is reused with a
	// different item set, quantity, or represented expiry instant.
	ErrReservationConflict = errors.New("order already has a different reservation request")
	// ErrReservationCoordinationUnavailable is returned when the cross-instance
	// coordination lease cannot be acquired.
	ErrReservationCoordinationUnavailable = errors.New("checkout reservation coordination is temporarily unavailable")
	// ErrInvalidExpiry is returned when expiresAt is absent, malformed, lacks
	// an explicit offset, or cannot be stored without precision loss.
	ErrInvalidExpiry = errors.New("expiresAt must be an RFC 3339 timestamp with an explicit offset and microsecond precision or less")
	// ErrExpiredExpiry is returned when a parsed expiry is not strictly later
	// than the authoritative reservation creation time.
	ErrExpiredExpiry = errors.New("expiresAt must be later than reservation creation time")
)

// VariantError wraps a stable reservation error with the public variant ID it
// concerns, so item-level failures can identify the failing variant without
// exposing internal identifiers or configuration.
type VariantError struct {
	VariantID uuid.UUID
	Err       error
}

func (e *VariantError) Error() string {
	return fmt.Sprintf("%s: variant %s", e.Err, e.VariantID)
}

func (e *VariantError) Unwrap() error { return e.Err }

// ValidateReservationItems enforces the checkout item invariants: a non-empty
// collection of unique variant IDs, each with a positive whole-number quantity.
func ValidateReservationItems(items []ReservationRequestItem) error {
	if len(items) == 0 {
		return ErrReservationValidation
	}
	seen := make(map[uuid.UUID]struct{}, len(items))
	for _, it := range items {
		if it.VariantID == uuid.Nil || it.Quantity <= 0 {
			return ErrReservationValidation
		}
		if _, dup := seen[it.VariantID]; dup {
			return ErrReservationValidation
		}
		seen[it.VariantID] = struct{}{}
	}
	return nil
}

// ValidateExpiry enforces the caller-owned expiry rule at the authoritative
// creation point: the expiry instant must be strictly later than the reference
// instant. The format/precision validation happens at the delivery boundary;
// this check owns the "no longer future" business rule and returns
// ErrExpiredExpiry for a parsed instant that is current or past.
func ValidateExpiry(expiry, reference time.Time) error {
	if !expiry.After(reference) {
		return ErrExpiredExpiry
	}
	return nil
}

// CreateReservationUseCase is the application contract for creating a checkout
// reservation. expiresAt is the caller-owned, UTC normalized expiry instant.
type CreateReservationUseCase interface {
	Create(ctx context.Context, orderID uuid.UUID, expiresAt time.Time, items []ReservationRequestItem) (ReservationResult, error)
}

// ReservationRepository is the persistence contract for checkout reservations.
type ReservationRepository interface {
	CreateReservation(ctx context.Context, input CreateReservationInput) (ReservationResult, error)
}

// ReservationLocker is the cross-instance coordination contract. It atomically
// acquires a short-lived lease over a canonical key set and releases it using
// an owner token.
type ReservationLocker interface {
	Acquire(ctx context.Context, keys []string) (token string, err error)
	Release(ctx context.Context, keys []string, token string) error
}
